version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_server
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=server
      - role=container
    environment:
      - MYSQL_USERNAME=zhb
      - MYSQL_PASSWORD=z_ru_feng98
      - MYSQL_ADDRESS=10.34.104.34:3306
networks:
  default:
    external:
      name: wxcb0
